server:
  port: 8080

spring:
  application:
    name: weather-backend
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/weather_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:0000}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
      database-platform: org.hibernate.dialect.MySQL8Dialect
    database: mysql
    properties:
      hibernate:
        format_sql: true
        jdbc.time_zone: Asia/Seoul
    open-in-view: false
  flyway:
    enabled: true
    locations: classpath:db/migration

logging:
  level:
    org.springframework.security: INFO
    org.hibernate.SQL: INFO

jwt:
  secret: ${JWT_SECRET:change-this-in-env}
  expiration-ms: ${JWT_EXPIRATION_MS:3600000}

kma:
  service-key: ${KMA_SERVICE_KEY:}
  # provider: data (기본, data.go.kr) | hub (기상청 API Hub)
  provider: hub
  # data.go.kr 기본 base-url (사용 중인 엔드포인트)
  data:
    base-url: https://apis.data.go.kr/1360000/VilageFcstInfoService_2.0
  # 기상청 API Hub 설정 (사용 전 실제 경로/헤더명을 확인해 수정하세요)
  hub:
    base-url: https://apihub.kma.go.kr/api/typ02/openApi/VilageFcstInfoService_2.0
    auth:
      mode: query        # header | query
      header-name: x-api-key
      query-name: authKey
